version: '2'
services:
  organizationaltimeline-app:
    image: organizationaltimeline
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://organizationaltimeline-postgresql:5432/OrganizationalTimeline
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://organizationaltimeline-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://organizationaltimeline-elasticsearch:9200
    ports:
      - 8080:8080
  organizationaltimeline-postgresql:
    extends:
      file: postgresql.yml
      service: organizationaltimeline-postgresql
  organizationaltimeline-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: organizationaltimeline-elasticsearch
